# Generated by Django 4.2.1 on 2023-05-30 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('season', models.CharField(max_length=150, verbose_name='Сезон')),
                ('kind', models.CharField(max_length=150, verbose_name='Тип')),
                ('picture', models.ImageField(blank=True, upload_to='clothes/heads/%Y/%m/%d', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'На голову',
                'verbose_name_plural': 'На голову',
                'ordering': ('added_at',),
            },
        ),
    ]
