# Generated by Django 4.2.1 on 2023-05-30 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('season', models.CharField(max_length=150, verbose_name='Сезон')),
                ('kind', models.CharField(max_length=150, verbose_name='Тип')),
                ('picture', models.ImageField(blank=True, upload_to='clothes/trousers/%Y/%m/%d', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Торс',
                'verbose_name_plural': 'Торс',
                'ordering': ('added_at',),
            },
        ),
        migrations.CreateModel(
            name='Аccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('season', models.CharField(max_length=150, verbose_name='Сезон')),
                ('kind', models.CharField(max_length=150, verbose_name='Тип')),
                ('picture', models.ImageField(blank=True, upload_to='clothes/trousers/%Y/%m/%d', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': 'Аксессуары',
                'ordering': ('added_at',),
            },
        ),
        migrations.CreateModel(
            name='Trousers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('season', models.CharField(max_length=150, verbose_name='Сезон')),
                ('kind', models.CharField(max_length=150, verbose_name='Тип')),
                ('picture', models.ImageField(blank=True, upload_to='clothes/trousers/%Y/%m/%d', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Штаны',
                'verbose_name_plural': 'Штаны',
                'ordering': ('added_at',),
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('season', models.CharField(max_length=150, verbose_name='Сезон')),
                ('kind', models.CharField(max_length=150, verbose_name='Тип')),
                ('picture', models.ImageField(blank=True, upload_to='clothes/trousers/%Y/%m/%d', verbose_name='Фото')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ботинки',
                'verbose_name_plural': 'Ботинки',
                'ordering': ('added_at',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('accessories', models.ManyToManyField(blank=True, to='main.аccessories')),
                ('body', models.ManyToManyField(blank=True, to='main.body')),
                ('head', models.ManyToManyField(blank=True, to='main.head')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shoes', models.ManyToManyField(blank=True, to='main.shoes')),
                ('trousers', models.ManyToManyField(blank=True, to='main.trousers')),
            ],
            options={
                'verbose_name': 'Образ',
                'verbose_name_plural': 'Образы',
                'ordering': ('added_at',),
            },
        ),
    ]
