# Generated by Django 4.2.1 on 2023-06-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_image_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='picture',
        ),
    ]
