# Generated by Django 4.2.1 on 2023-06-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_image_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to='clothes/images/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
