# Generated by Django 4.2.1 on 2023-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='picture',
            field=models.ImageField(blank=True, upload_to='main/static/clothes/bodies/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='head',
            name='picture',
            field=models.ImageField(blank=True, upload_to='main/static/clothes/heads/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to='main/static/clothes/images/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='picture',
            field=models.ImageField(blank=True, upload_to='main/static/clothes/shoes/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='trousers',
            name='picture',
            field=models.ImageField(blank=True, upload_to='main/static/clothes/trousers/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='аccessories',
            name='picture',
            field=models.ImageField(blank=True, upload_to='main/static/clothes/accessories/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
